M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu21.04.1} date sex 25 mar 2022 12:06:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-25T12:06:50+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu21.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.7162Y-4.8151
X5.9438Y-4.8151
T0
M30
